# Dependabot Configuration
# https://docs.github.com/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  # Note: pip default "auto" versioning strategy is "increase" for application,
  # "widen" for library (detected if pyproject.toml and published to PyPI):
  # https://github.com/dependabot/dependabot-core/issues/6685
  # This is error-prone and changes after publishing.
  # Therefore, set a versioning strategy explicitly.
  # Note: "widen" is unsupported for Python.  See:
  # https://github.com/dependabot/dependabot-core/issues/6630
  versioning-strategy: "increase-if-necessary"
