# Travis CI Configuration File
# https://docs.travis-ci.com/user/customizing-the-build/

language: python

# Test tox env matching Travis Python version
# https://stackoverflow.com/a/46103989
jobs:
  # Fail build immediately if any job fails
  fast_finish: true
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  # Travis CI doesn't support 3.9 yet:
  # https://travis-ci.community/t/10091/3
  - python: 3.8
    env: TOXENV=docs,lint,py38
  - python: pypy
    env: TOXENV=pypy
  - python: pypy3
    env: TOXENV=pypy3

install:
- pip install codecov coveralls tox

script:
- tox -vv

# Note:  Both codecov and coveralls detect branch/PR info from Travis CI
# https://github.com/codecov/codecov-node/blob/v1.0.1/lib/services/travis.js
# https://github.com/nickmerwin/node-coveralls/blob/2.11.5/lib/getOptions.js#L18
after_success:
- codecov
- coveralls
